{
    'name': 'Correspondence Management',
    'version': '1.0.0',
    'summary': 'Manage incoming and outgoing correspondences',
    'author': 'Your Company',
    'website': 'https://example.com',
    'license': 'AGPL-3',
    'category': 'Office',
    'depends': ['base', 'mail', 'web', 'document', 'sign_oca', 'base_tier_validation'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/mail_template.xml',
        'views/correspondence_views.xml',
        'reports/correspondence_report.xml',
        'views/correspondence_report_templates.xml',
    ],
    'installable': True,
    'application': True,
}
